export const siteAssets = {
  homeBackground: new URL("../../asset/0024-home.jpg", import.meta.url).href,
  horrorPoster: new URL("../../asset/f7c142692b-poster.jpg", import.meta.url).href,
  witchesPoster: new URL("../../asset/Photo2254.jpg", import.meta.url).href,
  vaguePoster: new URL("../../asset/Photo2252.jpg", import.meta.url).href,
  mnemosinePoster: new URL("../../asset/Photo2279.jpg", import.meta.url).href,
  angeloPoster: new URL("../../asset/poster2.jpg", import.meta.url).href,
  titleMark: new URL("../../asset/camaleonte stellato.jpg", import.meta.url).href,
  aboutPortrait: new URL("../../asset/IMG_20260329_115534_2.jpg", import.meta.url).href,
  aboutFlower: new URL("../../asset/Still 2025-12-10 202043_1.1.16.jpg", import.meta.url).href,
  aboutDarkFlower: new URL("../../asset/Still 2025-12-10 202043_1.2.3.jpg", import.meta.url).href,
  shortStills: [
    new URL("../../asset/_DSC0310.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0315.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0316.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0317.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0318.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0322.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0324.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0325.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0326.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0332.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0334.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0340.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0344.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0348.jpg", import.meta.url).href,
  ],
  shortBackgrounds: [
    new URL("../../asset/0024-home.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0322.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0324.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0332.jpg", import.meta.url).href,
    new URL("../../asset/_DSC0340.jpg", import.meta.url).href,
  ],
  musicStills: [
    new URL("../../asset/_FHD7913.JPG", import.meta.url).href,
    new URL("../../asset/_FHD7916.JPG", import.meta.url).href,
    new URL("../../asset/_FHD7921.JPG", import.meta.url).href,
    new URL("../../asset/_FHD7923.JPG", import.meta.url).href,
    new URL("../../asset/_FHD7935.JPG", import.meta.url).href,
    new URL("../../asset/_FHD7943.JPG", import.meta.url).href,
    new URL("../../asset/_FHD7949.JPG", import.meta.url).href,
    new URL("../../asset/_FHD7955.JPG", import.meta.url).href,
    new URL("../../asset/_FHD7957.JPG", import.meta.url).href,
  ],
  birdlandGrid: [
    new URL("../../asset/0004_4A.jpg", import.meta.url).href,
    new URL("../../asset/0005_5A.jpg", import.meta.url).href,
    new URL("../../asset/0006_6A.jpg", import.meta.url).href,
    new URL("../../asset/0007_7A.jpg", import.meta.url).href,
    new URL("../../asset/0008_8A.jpg", import.meta.url).href,
    new URL("../../asset/0009_9A.jpg", import.meta.url).href,
    new URL("../../asset/0011_11A.jpg", import.meta.url).href,
    new URL("../../asset/0026_26Amodif.jpg", import.meta.url).href,
  ],
  performanceStills: [
    new URL("../../asset/DSCF0908.JPG", import.meta.url).href,
    new URL("../../asset/DSCF0909.JPG", import.meta.url).href,
    new URL("../../asset/Roll1_00000030.JPG", import.meta.url).href,
    new URL("../../asset/IMG_20251028_144429.jpg", import.meta.url).href,
    new URL("../../asset/IMG_20260329_115806-2.jpg", import.meta.url).href,
    new URL("../../asset/photo_5769566269392144029_y.jpg", import.meta.url).href,
    new URL("../../asset/photo_5855028026864160293_y.jpg", import.meta.url).href,
    new URL("../../asset/photo_5855028026864160295_y.jpg", import.meta.url).href,
    new URL("../../asset/photo_5855028026864160296_y.jpg", import.meta.url).href,
  ],
  zine: [
    new URL("../../asset/Screenshot 2026-04-22 233006.png", import.meta.url).href,
    new URL("../../asset/Screenshot 2026-04-22 233415.png", import.meta.url).href,
    new URL("../../asset/918d36c7-a349-412d-b14a-9a9d84bcf91f.jpg", import.meta.url).href,
    new URL("../../asset/6fcd199e-2e57-4279-9574-c562570b98c6.jpg", import.meta.url).href,
  ],
};
